// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Actividade struct {
	IDActividad     int32          `json:"id_actividad"`
	NombreActividad string         `json:"nombre_actividad"`
	Descripcion     sql.NullString `json:"descripcion"`
}

type Aviso struct {
	IDAviso     int32          `json:"id_aviso"`
	Nombre      string         `json:"nombre"`
	Descripcion sql.NullString `json:"descripcion"`
	IDActividad sql.NullInt32  `json:"id_actividad"`
	IDPaciente  sql.NullInt32  `json:"id_paciente"`
	IDEnfermero sql.NullInt32  `json:"id_enfermero"`
}

type Enfermero struct {
	IDEnfermero int32  `json:"id_enfermero"`
	Nombre      string `json:"nombre"`
	Contrasena  string `json:"contrasena"`
}

type EnfermeroPaciente struct {
	IDEnfermero int32 `json:"id_enfermero"`
	IDPaciente  int32 `json:"id_paciente"`
}

type FamiliarPaciente struct {
	IDFamiliar int32 `json:"id_familiar"`
	IDPaciente int32 `json:"id_paciente"`
}

type Familiare struct {
	IDFamiliar int32  `json:"id_familiar"`
	Nombre     string `json:"nombre"`
	Contrasena string `json:"contrasena"`
}

type Paciente struct {
	IDPaciente int32  `json:"id_paciente"`
	Nombre     string `json:"nombre"`
}

type PacienteActividad struct {
	IDPaciente  int32 `json:"id_paciente"`
	IDActividad int32 `json:"id_actividad"`
}
