// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const asignarActividadAPaciente = `-- name: AsignarActividadAPaciente :exec

INSERT INTO Paciente_Actividad (id_paciente, id_actividad) VALUES ($1, $2)
`

type AsignarActividadAPacienteParams struct {
	IDPaciente  int32 `json:"id_paciente"`
	IDActividad int32 `json:"id_actividad"`
}

// creates de relaciones (¡NUEVOS! Para llenar las tablas puente)
func (q *Queries) AsignarActividadAPaciente(ctx context.Context, arg AsignarActividadAPacienteParams) error {
	_, err := q.db.ExecContext(ctx, asignarActividadAPaciente, arg.IDPaciente, arg.IDActividad)
	return err
}

const asignarPacienteAEnfermero = `-- name: AsignarPacienteAEnfermero :exec
INSERT INTO Enfermero_Paciente (id_enfermero, id_paciente) VALUES ($1, $2)
`

type AsignarPacienteAEnfermeroParams struct {
	IDEnfermero int32 `json:"id_enfermero"`
	IDPaciente  int32 `json:"id_paciente"`
}

func (q *Queries) AsignarPacienteAEnfermero(ctx context.Context, arg AsignarPacienteAEnfermeroParams) error {
	_, err := q.db.ExecContext(ctx, asignarPacienteAEnfermero, arg.IDEnfermero, arg.IDPaciente)
	return err
}

const asignarPacienteAFamiliar = `-- name: AsignarPacienteAFamiliar :exec
INSERT INTO Familiar_Paciente (id_familiar, id_paciente) VALUES ($1, $2)
`

type AsignarPacienteAFamiliarParams struct {
	IDFamiliar int32 `json:"id_familiar"`
	IDPaciente int32 `json:"id_paciente"`
}

func (q *Queries) AsignarPacienteAFamiliar(ctx context.Context, arg AsignarPacienteAFamiliarParams) error {
	_, err := q.db.ExecContext(ctx, asignarPacienteAFamiliar, arg.IDFamiliar, arg.IDPaciente)
	return err
}

const createActividad = `-- name: CreateActividad :one
INSERT INTO Actividades (nombre_actividad) VALUES ($1) RETURNING id_actividad, nombre_actividad, descripcion
`

func (q *Queries) CreateActividad(ctx context.Context, nombreActividad string) (Actividade, error) {
	row := q.db.QueryRowContext(ctx, createActividad, nombreActividad)
	var i Actividade
	err := row.Scan(&i.IDActividad, &i.NombreActividad, &i.Descripcion)
	return i, err
}

const createAviso = `-- name: CreateAviso :one
INSERT INTO Avisos (nombre, descripcion, id_paciente, id_enfermero) 
VALUES ($1, $2, $3, $4) RETURNING id_aviso, nombre, descripcion, id_actividad, id_paciente, id_enfermero
`

type CreateAvisoParams struct {
	Nombre      string         `json:"nombre"`
	Descripcion sql.NullString `json:"descripcion"`
	IDPaciente  sql.NullInt32  `json:"id_paciente"`
	IDEnfermero sql.NullInt32  `json:"id_enfermero"`
}

func (q *Queries) CreateAviso(ctx context.Context, arg CreateAvisoParams) (Aviso, error) {
	row := q.db.QueryRowContext(ctx, createAviso,
		arg.Nombre,
		arg.Descripcion,
		arg.IDPaciente,
		arg.IDEnfermero,
	)
	var i Aviso
	err := row.Scan(
		&i.IDAviso,
		&i.Nombre,
		&i.Descripcion,
		&i.IDActividad,
		&i.IDPaciente,
		&i.IDEnfermero,
	)
	return i, err
}

const createEnfermero = `-- name: CreateEnfermero :one

INSERT INTO Enfermeros (nombre, contrasena) VALUES ($1, $2) RETURNING id_enfermero, nombre, contrasena
`

type CreateEnfermeroParams struct {
	Nombre     string `json:"nombre"`
	Contrasena string `json:"contrasena"`
}

// create
func (q *Queries) CreateEnfermero(ctx context.Context, arg CreateEnfermeroParams) (Enfermero, error) {
	row := q.db.QueryRowContext(ctx, createEnfermero, arg.Nombre, arg.Contrasena)
	var i Enfermero
	err := row.Scan(&i.IDEnfermero, &i.Nombre, &i.Contrasena)
	return i, err
}

const createFamiliar = `-- name: CreateFamiliar :one
INSERT INTO Familiares (nombre, contrasena) VALUES ($1, $2) RETURNING id_familiar, nombre, contrasena
`

type CreateFamiliarParams struct {
	Nombre     string `json:"nombre"`
	Contrasena string `json:"contrasena"`
}

func (q *Queries) CreateFamiliar(ctx context.Context, arg CreateFamiliarParams) (Familiare, error) {
	row := q.db.QueryRowContext(ctx, createFamiliar, arg.Nombre, arg.Contrasena)
	var i Familiare
	err := row.Scan(&i.IDFamiliar, &i.Nombre, &i.Contrasena)
	return i, err
}

const createPaciente = `-- name: CreatePaciente :one
INSERT INTO Pacientes (nombre) VALUES ($1) RETURNING id_paciente, nombre
`

func (q *Queries) CreatePaciente(ctx context.Context, nombre string) (Paciente, error) {
	row := q.db.QueryRowContext(ctx, createPaciente, nombre)
	var i Paciente
	err := row.Scan(&i.IDPaciente, &i.Nombre)
	return i, err
}

const deleteActividad = `-- name: DeleteActividad :exec
DELETE FROM Actividades WHERE id_actividad = $1
`

func (q *Queries) DeleteActividad(ctx context.Context, idActividad int32) error {
	_, err := q.db.ExecContext(ctx, deleteActividad, idActividad)
	return err
}

const deleteAviso = `-- name: DeleteAviso :exec
DELETE FROM Avisos WHERE id_aviso = $1
`

func (q *Queries) DeleteAviso(ctx context.Context, idAviso int32) error {
	_, err := q.db.ExecContext(ctx, deleteAviso, idAviso)
	return err
}

const deleteEnfermero = `-- name: DeleteEnfermero :exec

DELETE FROM Enfermeros WHERE id_enfermero = $1
`

// delete
func (q *Queries) DeleteEnfermero(ctx context.Context, idEnfermero int32) error {
	_, err := q.db.ExecContext(ctx, deleteEnfermero, idEnfermero)
	return err
}

const deleteFamiliar = `-- name: DeleteFamiliar :exec
DELETE FROM Familiares WHERE id_familiar = $1
`

func (q *Queries) DeleteFamiliar(ctx context.Context, idFamiliar int32) error {
	_, err := q.db.ExecContext(ctx, deleteFamiliar, idFamiliar)
	return err
}

const deletePaciente = `-- name: DeletePaciente :exec
DELETE FROM Pacientes WHERE id_paciente = $1
`

func (q *Queries) DeletePaciente(ctx context.Context, idPaciente int32) error {
	_, err := q.db.ExecContext(ctx, deletePaciente, idPaciente)
	return err
}

const getActividad = `-- name: GetActividad :one
SELECT id_actividad, nombre_actividad, descripcion FROM Actividades WHERE id_actividad = $1
`

func (q *Queries) GetActividad(ctx context.Context, idActividad int32) (Actividade, error) {
	row := q.db.QueryRowContext(ctx, getActividad, idActividad)
	var i Actividade
	err := row.Scan(&i.IDActividad, &i.NombreActividad, &i.Descripcion)
	return i, err
}

const getAviso = `-- name: GetAviso :one
SELECT id_aviso, nombre, descripcion, id_actividad, id_paciente, id_enfermero FROM Avisos WHERE id_aviso = $1
`

func (q *Queries) GetAviso(ctx context.Context, idAviso int32) (Aviso, error) {
	row := q.db.QueryRowContext(ctx, getAviso, idAviso)
	var i Aviso
	err := row.Scan(
		&i.IDAviso,
		&i.Nombre,
		&i.Descripcion,
		&i.IDActividad,
		&i.IDPaciente,
		&i.IDEnfermero,
	)
	return i, err
}

const getEnfermero = `-- name: GetEnfermero :one

SELECT id_enfermero, nombre, contrasena FROM Enfermeros WHERE id_enfermero = $1
`

// getters
func (q *Queries) GetEnfermero(ctx context.Context, idEnfermero int32) (Enfermero, error) {
	row := q.db.QueryRowContext(ctx, getEnfermero, idEnfermero)
	var i Enfermero
	err := row.Scan(&i.IDEnfermero, &i.Nombre, &i.Contrasena)
	return i, err
}

const getFamiliar = `-- name: GetFamiliar :one
SELECT id_familiar, nombre, contrasena FROM Familiares WHERE id_familiar = $1
`

func (q *Queries) GetFamiliar(ctx context.Context, idFamiliar int32) (Familiare, error) {
	row := q.db.QueryRowContext(ctx, getFamiliar, idFamiliar)
	var i Familiare
	err := row.Scan(&i.IDFamiliar, &i.Nombre, &i.Contrasena)
	return i, err
}

const getPaciente = `-- name: GetPaciente :one
SELECT id_paciente, nombre FROM Pacientes WHERE id_paciente = $1
`

func (q *Queries) GetPaciente(ctx context.Context, idPaciente int32) (Paciente, error) {
	row := q.db.QueryRowContext(ctx, getPaciente, idPaciente)
	var i Paciente
	err := row.Scan(&i.IDPaciente, &i.Nombre)
	return i, err
}

const listActividades = `-- name: ListActividades :many
SELECT id_actividad, nombre_actividad, descripcion FROM Actividades ORDER BY nombre_actividad
`

func (q *Queries) ListActividades(ctx context.Context) ([]Actividade, error) {
	rows, err := q.db.QueryContext(ctx, listActividades)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Actividade
	for rows.Next() {
		var i Actividade
		if err := rows.Scan(&i.IDActividad, &i.NombreActividad, &i.Descripcion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActividadesPorPaciente = `-- name: ListActividadesPorPaciente :many

SELECT a.id_actividad, a.nombre_actividad, a.descripcion FROM Actividades a 
JOIN Paciente_Actividad pa ON a.id_actividad = pa.id_actividad 
WHERE pa.id_paciente = $1
`

// listers relacionales (Acá es donde usamos los JOIN con las tablas puente)
func (q *Queries) ListActividadesPorPaciente(ctx context.Context, idPaciente int32) ([]Actividade, error) {
	rows, err := q.db.QueryContext(ctx, listActividadesPorPaciente, idPaciente)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Actividade
	for rows.Next() {
		var i Actividade
		if err := rows.Scan(&i.IDActividad, &i.NombreActividad, &i.Descripcion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvisos = `-- name: ListAvisos :many
SELECT id_aviso, nombre, descripcion, id_actividad, id_paciente, id_enfermero FROM Avisos ORDER BY nombre
`

func (q *Queries) ListAvisos(ctx context.Context) ([]Aviso, error) {
	rows, err := q.db.QueryContext(ctx, listAvisos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Aviso
	for rows.Next() {
		var i Aviso
		if err := rows.Scan(
			&i.IDAviso,
			&i.Nombre,
			&i.Descripcion,
			&i.IDActividad,
			&i.IDPaciente,
			&i.IDEnfermero,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnfermeros = `-- name: ListEnfermeros :many

SELECT id_enfermero, nombre, contrasena FROM Enfermeros ORDER BY nombre
`

// listers básicos
func (q *Queries) ListEnfermeros(ctx context.Context) ([]Enfermero, error) {
	rows, err := q.db.QueryContext(ctx, listEnfermeros)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Enfermero
	for rows.Next() {
		var i Enfermero
		if err := rows.Scan(&i.IDEnfermero, &i.Nombre, &i.Contrasena); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFamiliares = `-- name: ListFamiliares :many
SELECT id_familiar, nombre, contrasena FROM Familiares ORDER BY nombre
`

func (q *Queries) ListFamiliares(ctx context.Context) ([]Familiare, error) {
	rows, err := q.db.QueryContext(ctx, listFamiliares)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Familiare
	for rows.Next() {
		var i Familiare
		if err := rows.Scan(&i.IDFamiliar, &i.Nombre, &i.Contrasena); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPacientes = `-- name: ListPacientes :many
SELECT id_paciente, nombre FROM Pacientes ORDER BY nombre
`

func (q *Queries) ListPacientes(ctx context.Context) ([]Paciente, error) {
	rows, err := q.db.QueryContext(ctx, listPacientes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Paciente
	for rows.Next() {
		var i Paciente
		if err := rows.Scan(&i.IDPaciente, &i.Nombre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPacientesPorEnfermero = `-- name: ListPacientesPorEnfermero :many
SELECT p.id_paciente, p.nombre FROM Pacientes p
JOIN Enfermero_Paciente ep ON p.id_paciente = ep.id_paciente
WHERE ep.id_enfermero = $1
`

func (q *Queries) ListPacientesPorEnfermero(ctx context.Context, idEnfermero int32) ([]Paciente, error) {
	rows, err := q.db.QueryContext(ctx, listPacientesPorEnfermero, idEnfermero)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Paciente
	for rows.Next() {
		var i Paciente
		if err := rows.Scan(&i.IDPaciente, &i.Nombre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPacientesPorFamiliar = `-- name: ListPacientesPorFamiliar :many
SELECT p.id_paciente, p.nombre FROM Pacientes p
JOIN Familiar_Paciente fp ON p.id_paciente = fp.id_paciente
WHERE fp.id_familiar = $1
`

func (q *Queries) ListPacientesPorFamiliar(ctx context.Context, idFamiliar int32) ([]Paciente, error) {
	rows, err := q.db.QueryContext(ctx, listPacientesPorFamiliar, idFamiliar)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Paciente
	for rows.Next() {
		var i Paciente
		if err := rows.Scan(&i.IDPaciente, &i.Nombre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActividad = `-- name: UpdateActividad :exec
UPDATE Actividades SET nombre_actividad = $2 WHERE id_actividad = $1
`

type UpdateActividadParams struct {
	IDActividad     int32  `json:"id_actividad"`
	NombreActividad string `json:"nombre_actividad"`
}

func (q *Queries) UpdateActividad(ctx context.Context, arg UpdateActividadParams) error {
	_, err := q.db.ExecContext(ctx, updateActividad, arg.IDActividad, arg.NombreActividad)
	return err
}

const updateAviso = `-- name: UpdateAviso :exec
UPDATE Avisos SET nombre = $2, descripcion = $3, id_paciente = $4, id_enfermero = $5 WHERE id_aviso = $1
`

type UpdateAvisoParams struct {
	IDAviso     int32          `json:"id_aviso"`
	Nombre      string         `json:"nombre"`
	Descripcion sql.NullString `json:"descripcion"`
	IDPaciente  sql.NullInt32  `json:"id_paciente"`
	IDEnfermero sql.NullInt32  `json:"id_enfermero"`
}

func (q *Queries) UpdateAviso(ctx context.Context, arg UpdateAvisoParams) error {
	_, err := q.db.ExecContext(ctx, updateAviso,
		arg.IDAviso,
		arg.Nombre,
		arg.Descripcion,
		arg.IDPaciente,
		arg.IDEnfermero,
	)
	return err
}

const updateEnfermero = `-- name: UpdateEnfermero :exec

UPDATE Enfermeros SET nombre = $2, contrasena = $3 WHERE id_enfermero = $1
`

type UpdateEnfermeroParams struct {
	IDEnfermero int32  `json:"id_enfermero"`
	Nombre      string `json:"nombre"`
	Contrasena  string `json:"contrasena"`
}

// update
func (q *Queries) UpdateEnfermero(ctx context.Context, arg UpdateEnfermeroParams) error {
	_, err := q.db.ExecContext(ctx, updateEnfermero, arg.IDEnfermero, arg.Nombre, arg.Contrasena)
	return err
}

const updateFamiliar = `-- name: UpdateFamiliar :exec
UPDATE Familiares SET nombre = $2, contrasena = $3 WHERE id_familiar = $1
`

type UpdateFamiliarParams struct {
	IDFamiliar int32  `json:"id_familiar"`
	Nombre     string `json:"nombre"`
	Contrasena string `json:"contrasena"`
}

func (q *Queries) UpdateFamiliar(ctx context.Context, arg UpdateFamiliarParams) error {
	_, err := q.db.ExecContext(ctx, updateFamiliar, arg.IDFamiliar, arg.Nombre, arg.Contrasena)
	return err
}

const updatePaciente = `-- name: UpdatePaciente :exec
UPDATE Pacientes SET nombre = $2 WHERE id_paciente = $1
`

type UpdatePacienteParams struct {
	IDPaciente int32  `json:"id_paciente"`
	Nombre     string `json:"nombre"`
}

func (q *Queries) UpdatePaciente(ctx context.Context, arg UpdatePacienteParams) error {
	_, err := q.db.ExecContext(ctx, updatePaciente, arg.IDPaciente, arg.Nombre)
	return err
}
